name: web-science
channels:
  - conda-forge
dependencies:
  - python-dotenv
  - pandas
  - nltk
  - numpy
  - scikit-learn
  - pip
  - pip:
    - TwitterAPI
    - mongoengine
    - gensim
    - python-dateutil
